hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('<str:name>/', views.greetings, name="greetings"),
]

sandboxplay/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('celebration/', include("celebration.urls")),
    path('tasks/', include("tasks.urls"))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

tasks/models.py
from django.db import models

# Create your models here.

celebration/views.py
from django.shortcuts import render
from pyluach import dates

# Create your views here.
def index(request):
    # Jesus Christ Celebration at day 14th, Nisan (when he died)
    celebrationDate = dates.HebrewDate(
        dates.HebrewDate.today().year,
        1,
        14
    )

    return render(request, "celebration/index.html", {
        "date": celebrationDate.to_greg,
        "isCeleb": celebrationDate.to_jd == dates.GregorianDate.today().to_jd
    })

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'hello/index.html')


def greetings(request, name):
    return render(request, 'hello/greet.html', {
        "name": name.capitalize()
    })

tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django import forms

class NewTaskForm(forms.Form):
    """
    • Labels are put on by default and named after the variable name (in this case, new_task will be parsed as "New task:", if set to True)

    • To specify attributes, we need to add a widget as below (the details of why it is implemented this way is yet unknown to me).

    """
    new_task = forms.CharField(label=False, widget=forms.TextInput(attrs={"class": "form-control mt-1", "style": "width: 35%"}), required=True)
    """
    • In order to use min_value and max_value (and potentially other tools for validation) while using a widget (like 
    in this case, for a CSS class), you must match the type of the widget and the type of field (e.g. IntegerField/NumberInput,
    and in other cases, probably CharField/TextInput). min and max_value didn't work when those fields weren't matched.

    • Multiple attrs (attributes) can be placed in a dictionary format. In the first field I decided to use inline-css, while the second
    field I opted to use the class "input-width", which was written in the te mplate file style tag.

    """
    # priority = forms.IntegerField(min_value=0, max_value=5, widget=forms.NumberInput(attrs={"class": "form-control input-width mt-1"}))


# Create your views here.
def index(request):

    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    # If the route receives a post request
    if request.method == 'POST':
        # Store form fields as Django form
        form = NewTaskForm(request.POST)
        # Use Django built-in form validation 
        if form.is_valid():
            task = form.cleaned_data["new_task"]
            request.session["tasks"] += [task]
            return redirect(reverse("tasks:index")) # Do a "reverse engineer" to find where the url from tasks:index is
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
        
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

celebration/templates/celebration/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Is it celebration?</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    </head>
    <style>
        body {
            margin: 1rem;
        }
        
        main {
            display: flex;
            justify-content: center;            
            align-items: center;
            height: 90vh;
        }
    </style>
    <body>
        <header>
            <p>This year, the celebration will occur at {{ date }}.</p>
        </header>
        <main>
            {% if isCeleb %}
            <h1 class="display-1">YES</h1>
            {% else %}
            <h1 class="display-1">NO</h1>
            {% endif %}
        </main>
    </body>
</html>

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello {{ name }}</title>
    </head>
    <body>
        <h1 style="color: rgb(179, 38, 38)">Hello {{ name }}!</h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello page</title>
    </head>
    <body>
        <h1 style="color: rgb(179, 38, 38)">Hello world</h1>
    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1 class="text-center">Add tasks</h1>
<form action="{% url 'tasks:add' %}" method="POST">
    <label for="id_new_task">Insert a task: </label>
    {{ form }}
    <br>
    <input type="submit" value="Add task" class="btn btn-success mt-2">
    {% csrf_token %}
</form>
<a href="{% url 'tasks:index' %}" class="btn btn-primary mt-1">Cancel</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1 class="text-center">Your tasks</h1>

<a href="{% url 'tasks:add' %}" class="btn btn-primary m-3">Add tasks</a>

<ul>
{% for task in tasks %}
    <li>{{ task }}</li>
{% empty %}
    <li>No tasks</li>
{% endfor %}
</ul>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}Tasks</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <style>
        body {
            margin: 1em;
        }

        .input-width {
            width: 35%;
        }
    </style>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>